
	var Music_list =	{"geography_club": {
									"songs" : { 1 : "Tangram",
						 						2 : "Call it",
												3 : "Away",
												4 : "Deeper",
												5 : "Fear for a meadow",
												6 : "Shearing",
												7 : "Yewi",
												8 : "Raincabin"
												},
									"times":  { 1 : "4:20",
												2 : "2:25",
												3 : "4:27",
												4 : "3:40",
												5 : "2:45",
												6 : "1:35",
												7 : "5:15",
												8 : "2:32"
												},
									"pictures": { 1 : "magic.png",
												  2 : "explore.png",
												  3 : "bike.png",
												  4 : "drumkat.png",
												  5 : "maski.png",
												  6 : "moon.png",
												  7 : "uke.png"
												},
									"cover": "tangram.jpeg",
									"name" : "Geography Club",
									"description" : "<i>All song written and recorded by Connor Walsh.</i> <br><br> Geography Club is my most recent project, begun in late spring 2011. This collection of songs is, in a way, a celebration of cosmic strangeness, but also indulges in the things I love most. At the root of it all, though, is a bit of adventure."
									},
									
							"mattress": {
										"songs" : { 1 : "Tightrope",
							 						2 : "Tigerbomb!",
													3 : "Whizkidz",
													4 : "One hundred trillion years of solitude",
													5 : "Twink"
													},
										"times":  { 1 : "3:03",
													2 : "3:13",
													3 : "3:55",
													4 : "2:28",
													5 : "0:49"
													},
										"pictures": { 1 : "tom2.png",
													  2 : "three.png",
													  3 : "basement.png",
													  4 : "float.png",
													  5 : "floor.png",
													  6 : "dudes.png",
													  7 : "yo.png",
													  8 : "zine.png"
													},
										"cover": "cover.png",
										"name" : "Mattress",
										"description" : '<i>Patrick Hannon</i> : Drums <br> <i>Thomas vonHalle</i> : Double Bass, vocals <br> <i>Connor Walsh</i> : Keyboard, vocals <br><br> <i>All songs written and recorded by Mattress.</i> <br><br> Mattress was formed in the fall of 2008. My two band-mates and I lived in the same <a target="_blank" href="http://www.youtube.com/watch?v=rkrhf8YAhqI"> house </a> where we occasionally organized house shows. Initially, we weren\'t too serious but some <a target="_blank" href="http://www.npr.org/blogs/therecord/2010/10/25/130809635/screaming-females-diy-in-new-brunswick"> friends </a> of ours convinced us to start playing shows. Eventually we released a 7" record and toured the East coast several times. '
										},
										
							"snowbaby": {
										"songs" : { 1 : "Summer, the Banshee!",
													2 : "Forest Hymn, youll be warned",
													3 : "Self Portrait (I love you)",
													4 : "Little One, Wake Up",
													5 : "an uneasy interlude",
													6 : "How Peter Was The Phantom Scarecro",
													7 : "quiet prayer",
													8 : "ladakhi soks",
													9 : "Bullfrog; Forest Hymn, youll be warned; live at Alfa Art",
													10: "hush child, cellar door",
													11: "in the tunnels"
													},
										"times":  { 1 : "5:43",
													2 : "5:47",
													3 : "2:06",
													4 : "2:07",
													5 : "0:32",
													6 : "7:20",
													7 : "6:00",
													8 : "4:57",
													9 : "6:48",
													10: "5:40",
													11: "3:34"
													},
										"pictures": {1 : "dark.png",
													 2 : "march.png",
													 3 : "philly.png",
													 4 : "books.png",
													 5 : "attic.png",
													 6 : "crew.jpg",
													 7 : "alpha.png",
													 8 : "farm.png"
													},
										"cover": "cover.jpg",
										"name" : "Snowbaby",
										"description" : '<i>Lillyan Ling</i> : toy piano, vocals, ukulele <br> <i>Patrick Hannon</i> : guitar, vocals, sampler <br> <i>Michael Pechter</i> : percussion, vocals <br> <i>Connor Walsh</i> : banjo, vocals, clarinet, ukulele, treatments <br><i>James Keene </i> : guest violinist on \"ladakhi soks\"<br><br> <i>All songs written and recorded by Connor Walsh.</i> <br><br> While living in an uninsulated attic during the cold winter of 2008/2009, I began writing songs for a new project. The sonic landscape of this collection is often marked by its gloomy atmosphere and the fablelike narratives which center on the misadventures of children. During spring 2009, I organized a group of musicians to perform the songs I had composed up in my attic. Snowbaby remained active for nearly two years and performed mainly across the North Eastern region of the United States.'
										},
										
							"ira_and_friends": {
										"songs" : { 1 : "broken fingers",
													2 : "Barrels",
													3 : "5ive in F",
													4 : "Ides of March",
													5 : "Saturday Sunday",
													6 : "In the Echo Box",
													7 : "--",
													8 : "dub dub",
													9 : "horseapples",
													10: "My Bicycle"
													},
										"times":  { 1 : "4:21",
													2 : "3:54",
													3 : "0:39",
													4 : "4:29",
													5 : "3:17",
													6 : "3:16",
													7 : "2:36",
													8 : "2:56",
													9 : "3:49",
													10: "4:17"
													},
										"pictures": {1 : "littlebig.png",
													 2 : "tom.png",
													 3 : "meat_town.png",
													 4 : "brow.png",
													 5 : "newyear.png",
													 6 : "tent.png",
													 7 : "tux.png"
													},
										"cover": "cover.png",
										"name" : "ira & friends",
										"description" : '<i>James Brehm</i> : guitar, singing saw, vocals, ukulele, treatments <br> <i>Edward Vasconcellos III</i> : guitar <br> <i>Thomas vonHalle</i> : Double Bass <br> <i>Nneka Anyoaku</i> : vocals, drums <br> <i>Michael Pechter</i> : drums <br> <i>Hank Mason</i> : electric bass, guitar on track 8 & 9 <br> <i>Douglass Vento</i> : drums & percussion on track 9 <br> <i>Connor Walsh</i> : keyboards, guitar, bass, drums, vocals, treatments <br><br> <i>All songs written and recorded by Connor Walsh, except tracks 8 & 9 written by Hank Mason.</i> <br><br> Many of these songs were written while I was still in high school, so I ask the kind listener to excuse the cloud of puerility surrounding this collection of music. Although I still had much growing to do when these songs were composed, I had a great deal of fun writing and recording them. When I entered college, I organized a group of musicians to perform these songs.'
										}
						};
